#!/usr/bin/env bash
# Configures a new HAproxy as a load balancer

# Installing HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configuring haproxy configuration file to distribute requests using a roundrobin algorithm
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend gyebi.tech
    timeout client  30000
    bind 0:80
    default_backend gyebi.tech_backend

backend gyebi.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 312908-web-01 54.237.13.5:80 check
    server 312908-web-02 3.94.185.151:80 check
EOT

# Restarting the HAproxy service
sudo service haproxy restart
