#!/usr/bin/env bash
# A script that displays "Best School" 10 times but prints “bad luck & good luck” at 4th & 8th iteration
i=0
while ((i < 10))
do
	((i++))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
